name: qclay
description: A new Flutter project.

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"

dependency_overrides:
  flutter_svg: ^1.1.4

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  #https://pub.dev/packages/flutter_bloc
  flutter_bloc: ^7.0.1
  #https://pub.dev/packages/rxdart
  rxdart: ^0.27.1
  #https://pub.dev/packages/flutter_secure_storage
  flutter_secure_storage: ^6.0.0
  #https://pub.dev/packages/shared_preferences
  shared_preferences: ^2.0.5
  #https://pub.dev/packages/dartz
  dartz: ^0.9.2
  #https://pub.dev/packages/data_connection_checker
  data_connection_checker: ^0.3.4
  #https://pub.dev/packages/dio
  dio: ^4.0.0
  #https://pub.dev/packages/retrofit
  retrofit: ^3.0.1+1
  #https://pub.dev/packages/json_annotation
  json_annotation: ^4.0.1
  #https://pub.dev/packages/formz
  formz: ^0.4.0
  #https://pub.dev/packages/flutter_svg
  flutter_svg: ^0.23.0+1
  #https://pub.dev/packages/get_it
  get_it: ^7.2.0
  #https://pub.dev/packages/intl
  intl: ^0.17.0
  #https://pub.dev/packages/modal_bottom_sheet
  modal_bottom_sheet: ^2.0.1
  #https://pub.dev/packages/image_picker
  image_picker: ^0.8.4+4
  #https://pub.dev/packages/file_picker
  file_picker: ^4.3.2
  #https://pub.dev/packages/flutter_keyboard_visibility
  flutter_keyboard_visibility: ^5.2.0
  #https://pub.dev/packages/path_provider
  path_provider: ^2.0.8
  #https://pub.dev/packages/flutter_native_timezone
  flutter_native_timezone: ^1.1.0
  #https://pub.dev/packages/libphonenumber_plugin
  libphonenumber_plugin: ^0.2.3
  #https://pub.dev/packages/flutter_libphonenumber
  flutter_libphonenumber: ^1.2.2
  #https://pub.dev/packages/flutter_country
  flutter_country: ^0.1.1
  #https://pub.dev/packages/devicelocale
  devicelocale: ^0.5.0
  #https://pub.dev/packages/freezed
  freezed: ^2.1.0+1
  #https://pub.dev/packages/permission_handler
  permission_handler: ^9.2.0
  #https://pub.dev/packages/sms_autofill
  sms_autofill: ^2.2.0
  #https://pub.dev/packages/auto_size_text
  auto_size_text: ^3.0.0
  #https://pub.dev/packages/flutter_scale_tap
  flutter_scale_tap: ^1.0.5
  #https://pub.dev/packages/url_launcher
  url_launcher: ^6.0.20
  #https://pub.dev/packages/firebase_messaging
  firebase_messaging: ^11.2.8
  #https://pub.dev/packages/firebase_core
  firebase_core: ^1.13.1
  #https://pub.dev/packages/overlay_support
  overlay_support: ^1.2.1
  #https://pub.dev/packages/mask_text_input_formatter/install
  mask_text_input_formatter: ^2.1.0
  #https://pub.dev/packages/package_info_plus
  package_info_plus: ^1.4.0
  #https://pub.dev/packages/bottom_sheet
  bottom_sheet: ^2.1.0
  #https://pub.dev/packages/cupertino_icons
  cupertino_icons: ^1.0.4
  #https://pub.dev/packages/pinput
  pinput: ^1.2.0
  #https://pub.dev/packages/carousel_slider
  carousel_slider: ^4.1.1
  #https://pub.dev/packages/dropdown_button2
  dropdown_button2: ^1.3.2
  #https://pub.dev/packages/flutter_staggered_grid_view
  flutter_staggered_grid_view: ^0.6.1
  #https://pub.dev/packages/infinite_scroll_pagination
  infinite_scroll_pagination: ^3.1.0
  #https://pub.dev/packages/video_player
  video_player: ^2.4.2
  #https://pub.dev/packages/google_maps_flutter
  google_maps_flutter: ^2.1.5
  #https://pub.dev/packages/geolocator
  geolocator: ^8.2.1
  #https://pub.dev/packages/geocoding
  geocoding: ^2.0.4
  #https://pub.dev/packages/flutter_switch
  flutter_switch: ^0.3.2
  #https://pub.dev/packages/fl_chart
  fl_chart: ^0.51.0
  #https://pub.dev/packages/intl_phone_field
  intl_phone_field: ^3.1.0
  #https://pub.dev/packages/table_calendar
  table_calendar: ^3.0.6
  #https://pub.dev/packages/collection
  collection: ^1.16.0
  #https://pub.dev/packages/cached_network_image
  cached_network_image: ^3.2.1
  #https://pub.dev/packages/flutter_html
  flutter_html: ^3.0.0-alpha.5
  #https://pub.dev/packages/webview_flutter
  webview_flutter: ^2.0.4
  #https://pub.dev/packages/shimmer
  shimmer: ^2.0.0
  #https://pub.dev/packages/percent_indicator
  percent_indicator: ^4.2.2
  #https://pub.dev/packages/dotted_border
  dotted_border: ^2.0.0+2
  #https://pub.dev/packages/expansion_widget
  expansion_widget: ^0.0.3
  #https://pub.dev/packages/pull_to_refresh
  pull_to_refresh: ^2.0.0
  #https://pub.dev/packages/flutter_local_notifications
  flutter_local_notifications: 9.7.0
  #https://pub.dev/packages/dropdown_search
  dropdown_search: ^5.0.2
  #https://pub.dev/packages/device_info
  device_info: ^2.0.3
  #https://pub.dev/packages/syncfusion_flutter_datepicker
  syncfusion_flutter_datepicker: ^20.2.46
  #https://pub.dev/packages/simple_gradient_text
  simple_gradient_text: ^1.2.3
  flutter_driver:
    sdk: flutter

dev_dependencies:
  retrofit_generator: ^4.0.1
  hive_generator: ^1.1.0
  build_runner: ^2.0.3
  json_serializable: ^6.1.4
  analyzer: ^4.7.0
  flutter_launcher_icons: ^0.9.3
  change_app_package_name: ^1.0.0
  flutter_gen_runner: ^4.1.5

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/i18n/
    - assets/fonts/

  fonts:
    - family: Helios
      fonts:
        - asset: assets/fonts/Helios-ExtraLight.ttf
          weight: 100
        - asset: assets/fonts/Helios-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/Helios-ExtraLight.ttf
          weight: 300
        - asset: assets/fonts/Helios-Extra.ttf
          weight: 400
        - asset: assets/fonts/Helios-Extra.ttf
          weight: 500
        - asset: assets/fonts/Helios-Extra Bold.ttf
          weight: 600
        - asset: assets/fonts/Helios-Extra Bold.ttf
          weight: 700
        - asset: assets/fonts/Helios-Extra Black.ttf
          weight: 800
        - asset: assets/fonts/Helios-Extra Black.ttf
          weight: 900
    - family: Monoska
      fonts:
        - asset: assets/fonts/Monoska.ttf
        

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/launcher_icon.png"
